# Прогнозируем задержки самолетов

In [2]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import roc_auc_score
import pandas as pd

from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

In [3]:
RANDOM_STATE = 111
DATASET_PATH = 'https://raw.githubusercontent.com/evgpat/edu_stepik_practical_ml/main/datasets/flight_delays_train.csv'

In [4]:
data = pd.read_csv(DATASET_PATH)

x = data.drop('dep_delayed_15min', axis=1)
y = data['dep_delayed_15min'] == 'Y'

x.head()

  Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0   c-8       c-21       c-7     1934            AA    ATL  DFW       732
1   c-4       c-20       c-3     1548            US    PIT  MCO       834
2   c-9        c-2       c-5     1422            XE    RDU  CLE       416
3  c-11       c-25       c-6     1015            OO    DEN  MEM       872
4  c-10        c-7       c-6     1828            WN    MDW  OMA       423

Создайте список номеров колонок с категориальными признаками для бустингов

## Quiz
Какой длины получился список?

(подсказка: колонка `DepTime` числовая)

In [5]:
# your code here
cat_features = x.select_dtypes(include='object').columns.to_list()
cat_features

['Month', 'DayofMonth', 'DayOfWeek', 'UniqueCarrier', 'Origin', 'Dest']

Разобъем данные на обучение и контроль

In [6]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=RANDOM_STATE)

In [7]:
xtrain.head()

      Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
41207   c-4       c-18       c-1     1457            CO    EWR  TPA       998
28283  c-11        c-1       c-2     1225            UA    DEN  BOS      1754
34619   c-6       c-16       c-5     1650            YV    IAD  CAE       401
8789    c-5       c-18       c-4      923            AA    SLC  DFW       988
38315   c-2       c-14       c-2     1839            AA    STL  SAN      1558

## Модели с параметрами по умолчанию

Обучите CatBoost с гиперпараметрами по умолчанию.

## Quiz
Чему равен ROC-AUC на тестовых данных? Ответ округлите до сотых.

In [8]:
# your code here
cb = CatBoostClassifier(random_seed=RANDOM_STATE, verbose=False)
cb.fit(xtrain, ytrain, cat_features=cat_features)

cb_pred = cb.predict_proba(xtest)[:,1]
roc_auc_score(ytest, cb_pred)

0.7656748885779602

Обучите LightGBM с гиперпараметрами по умолчанию.

## Quiz
Чему равен ROC-AUC на тестовых данных? Ответ округлите до сотых.

In [9]:
for c in x.columns:
    col_type = x[c].dtype
    if col_type == 'object' or col_type.name == 'category':
        xtrain[c] = xtrain[c].astype('category')
        xtest[c] = xtest[c].astype('category')

In [10]:
# your code here
lgbm = LGBMClassifier(random_state=RANDOM_STATE)
lgbm.fit(xtrain, ytrain)

lgbm_pred = lgbm.predict_proba(xtest)[:,1]
roc_auc_score(ytest, lgbm_pred)

[LightGBM] [Info] Number of positive: 14346, number of negative: 60654
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000984 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 75000, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.191280 -> initscore=-1.441714
[LightGBM] [Info] Start training from score -1.441714

0.7341149074685321

## Optuna

Выделим дополнительную валидационную выборку.

In [11]:
xtrain_new, xval, ytrain_new, yval = train_test_split(xtrain, ytrain, test_size=0.25, random_state=RANDOM_STATE)

Создайте функцию objective_lgbm, в которой среди гиперпараметров

* num_leaves = trial.suggest_int("num_leaves", 10, 100)
* n_estimators = trial.suggest_int("n_estimators", 10, 1000)

подберите оптимальные, обучая LGBM на Xtrain_new, ytrain_new и проверяя качество (ROC-AUC) на Xval.

Используйте 30 эпох обучения Optuna.

In [12]:
import optuna

# your code here
def objective_lgbm(trial):
    num_leaves = trial.suggest_int('num_leaves', 10, 100)
    n_estimators = trial.suggest_int('n_estimators', 10, 1000)

    model = LGBMClassifier(num_leaves=num_leaves, n_estimators=n_estimators, random_state=RANDOM_STATE, verbose=-1)
    model.fit(xtrain_new, ytrain_new)
    pred = model.predict_proba(xval)[:,1]

    score = roc_auc_score(yval, pred)

    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective_lgbm, n_trials=30)

[I 2026-04-08 19:54:17,733] A new study created in memory with name: no-name-39f40db1-a3fc-4526-956d-03ddaf7b6619
[I 2026-04-08 19:54:19,778] Trial 0 finished with value: 0.7182771043281786 and parameters: {'num_leaves': 35, 'n_estimators': 780}. Best is trial 0 with value: 0.7182771043281786.
[I 2026-04-08 19:54:20,992] Trial 1 finished with value: 0.7182382734884004 and parameters: {'num_leaves': 53, 'n_estimators': 361}. Best is trial 0 with value: 0.7182771043281786.
[I 2026-04-08 19:54:22,486] Trial 2 finished with value: 0.7150830530447179 and parameters: {'num_leaves': 24, 'n_estimators': 863}. Best is trial 0 with value: 0.7182771043281786.
[I 2026-04-08 19:54:24,554] Trial 3 finished with value: 0.7183431989858152 and parameters: {'num_leaves': 91, 'n_estimators': 533}. Best is trial 3 with value: 0.7183431989858152.
[I 2026-04-08 19:54:28,466] Trial 4 finished with value: 0.7186117622103896 and parameters: {'num_leaves': 99, 'n_estimators': 857}. Best is trial 4 with value: 0.7186117622103896.
[I 2026-04-08 19:54:35,466] Trial 5 finished with value: 0.7192391223945146 and parameters: {'num_leaves': 59, 'n_estimators': 625}. Best is trial 5 with value: 0.7192391223945146.
[I 2026-04-08 19:54:38,521] Trial 6 finished with value: 0.712203942713529 and parameters: {'num_leaves': 29, 'n_estimators': 1000}. Best is trial 5 with value: 0.7192391223945146.
[I 2026-04-08 19:54:40,283] Trial 7 finished with value: 0.7168817158165813 and parameters: {'num_leaves': 37, 'n_estimators': 713}. Best is trial 5 with value: 0.7192391223945146.
[I 2026-04-08 19:54:41,813] Trial 8 finished with value: 0.7194227876983315 and parameters: {'num_leaves': 77, 'n_estimators': 405}. Best is trial 8 with value: 0.7194227876983315.
[I 2026-04-08 19:54:43,874] Trial 9 finished with value: 0.7146260369021988 and parameters: {'num_leaves': 23, 'n_estimators': 906}. Best is trial 8 with value: 0.7194227876983315.
[I 2026-04-08 19:54:44,307] Trial 10 finished with value: 0.7221934275048505 and parameters: {'num_leaves': 79, 'n_estimators': 70}. Best is trial 10 with value: 0.7221934275048505.
[I 2026-04-08 19:54:44,714] Trial 11 finished with value: 0.724185349082123 and parameters: {'num_leaves': 78, 'n_estimators': 72}. Best is trial 11 with value: 0.724185349082123.
[I 2026-04-08 19:54:44,891] Trial 12 finished with value: 0.7248374970470288 and parameters: {'num_leaves': 73, 'n_estimators': 23}. Best is trial 12 with value: 0.7248374970470288.
[I 2026-04-08 19:54:45,051] Trial 13 finished with value: 0.7255713268254917 and parameters: {'num_leaves': 66, 'n_estimators': 29}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:46,133] Trial 14 finished with value: 0.721060042090072 and parameters: {'num_leaves': 59, 'n_estimators': 242}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:47,213] Trial 15 finished with value: 0.7190951285039489 and parameters: {'num_leaves': 66, 'n_estimators': 199}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:47,305] Trial 16 finished with value: 0.7165977573061184 and parameters: {'num_leaves': 11, 'n_estimators': 16}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:47,898] Trial 17 finished with value: 0.7223448220966446 and parameters: {'num_leaves': 47, 'n_estimators': 193}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:49,067] Trial 18 finished with value: 0.7208543574159338 and parameters: {'num_leaves': 73, 'n_estimators': 327}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:49,734] Trial 19 finished with value: 0.723627592036217 and parameters: {'num_leaves': 85, 'n_estimators': 123}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:51,965] Trial 20 finished with value: 0.7200841545614342 and parameters: {'num_leaves': 67, 'n_estimators': 442}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:52,086] Trial 21 finished with value: 0.7223365990952799 and parameters: {'num_leaves': 88, 'n_estimators': 14}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:52,638] Trial 22 finished with value: 0.7220861447470444 and parameters: {'num_leaves': 69, 'n_estimators': 133}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:53,647] Trial 23 finished with value: 0.7206581017833606 and parameters: {'num_leaves': 80, 'n_estimators': 269}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:54,358] Trial 24 finished with value: 0.7253128139359187 and parameters: {'num_leaves': 100, 'n_estimators': 98}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:55,518] Trial 25 finished with value: 0.7239545385704812 and parameters: {'num_leaves': 100, 'n_estimators': 154}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:56,355] Trial 26 finished with value: 0.7201283760354404 and parameters: {'num_leaves': 47, 'n_estimators': 281}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:56,891] Trial 27 finished with value: 0.721493394261997 and parameters: {'num_leaves': 96, 'n_estimators': 84}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:57,008] Trial 28 finished with value: 0.7201013771809592 and parameters: {'num_leaves': 92, 'n_estimators': 11}. Best is trial 13 with value: 0.7255713268254917.
[I 2026-04-08 19:54:58,987] Trial 29 finished with value: 0.7178863473033233 and parameters: {'num_leaves': 61, 'n_estimators': 520}. Best is trial 13 with value: 0.7255713268254917.

In [13]:
study.best_params

{'num_leaves': 66, 'n_estimators': 29}

Обучите модель с найденными гиперпараметрами на Xtrain, ytrain и оцените ROC-AUC на тестовых данных.

In [14]:
# your code here
best_lgbm = LGBMClassifier(**study.best_params, random_state=RANDOM_STATE)
best_lgbm.fit(xtrain, ytrain)

final_preds = best_lgbm.predict_proba(xtest)[:, 1]
final_roc_auc = roc_auc_score(ytest, final_preds)

print(f"Final LightGBM ROC-AUC: {final_roc_auc:.2f}")
print(f"Количество деревьев: {study.best_params['n_estimators']}")

Final LightGBM ROC-AUC: 0.73
Количество деревьев: 29

## Quiz

Чему равно количество деревьев в LGBM после подбора гиперпараметров?

## Работа над улучшением модели

* Попробуйте при помощи Optuna подобрать и другие гиперпарамтеры
* Также подберите гиперпараметры у CatBoost (а не только у LightGBM)

In [15]:
# your code here
def objective_lgbm_pro(trial):
    params = {'num_leaves': trial.suggest_int('num_leaves', 10, 100),
              'n_estimators': trial.suggest_int('n_estimators', 10, 1000),
              'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
              'max_depth': trial.suggest_int('max_depth', 3, 12)}
    
    model = LGBMClassifier(**params, random_state=RANDOM_STATE, verbose=-1)
    model.fit(xtrain_new, ytrain_new)

    preds = model.predict_proba(xval)[:,1]
    return roc_auc_score(yval, preds)

lgbm_study = optuna.create_study(direction='maximize')
lgbm_study.optimize(objective_lgbm_pro, n_trials=30)

[I 2026-04-08 19:54:59,382] A new study created in memory with name: no-name-b820a3b7-7d5f-4988-960b-937a66a66c3c
[I 2026-04-08 19:55:00,206] Trial 0 finished with value: 0.7111299090952681 and parameters: {'num_leaves': 70, 'n_estimators': 240, 'learning_rate': 0.17450714732899933, 'max_depth': 6}. Best is trial 0 with value: 0.7111299090952681.
[I 2026-04-08 19:55:00,764] Trial 1 finished with value: 0.7265362868989825 and parameters: {'num_leaves': 15, 'n_estimators': 404, 'learning_rate': 0.042704193083745824, 'max_depth': 7}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:00,982] Trial 2 finished with value: 0.7256137666492022 and parameters: {'num_leaves': 90, 'n_estimators': 187, 'learning_rate': 0.028326766588444782, 'max_depth': 3}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:03,984] Trial 3 finished with value: 0.72322517662276 and parameters: {'num_leaves': 81, 'n_estimators': 562, 'learning_rate': 0.06459258760774393, 'max_depth': 12}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:04,963] Trial 4 finished with value: 0.7049051336087881 and parameters: {'num_leaves': 38, 'n_estimators': 730, 'learning_rate': 0.16225341365412704, 'max_depth': 4}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:05,344] Trial 5 finished with value: 0.7263389988229046 and parameters: {'num_leaves': 20, 'n_estimators': 174, 'learning_rate': 0.01842334154176985, 'max_depth': 6}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:06,961] Trial 6 finished with value: 0.7139987680847555 and parameters: {'num_leaves': 55, 'n_estimators': 471, 'learning_rate': 0.15130899712041493, 'max_depth': 7}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:08,636] Trial 7 finished with value: 0.7090577858446843 and parameters: {'num_leaves': 54, 'n_estimators': 951, 'learning_rate': 0.12067977821555927, 'max_depth': 4}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:08,860] Trial 8 finished with value: 0.7202782539403161 and parameters: {'num_leaves': 22, 'n_estimators': 92, 'learning_rate': 0.17474880046279384, 'max_depth': 8}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:11,646] Trial 9 finished with value: 0.724056065227332 and parameters: {'num_leaves': 36, 'n_estimators': 979, 'learning_rate': 0.01566042224282044, 'max_depth': 8}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:12,321] Trial 10 finished with value: 0.726291405918339 and parameters: {'num_leaves': 10, 'n_estimators': 449, 'learning_rate': 0.05351696864917709, 'max_depth': 10}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:12,816] Trial 11 finished with value: 0.7259311196818744 and parameters: {'num_leaves': 10, 'n_estimators': 307, 'learning_rate': 0.015484872612194962, 'max_depth': 6}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:12,908] Trial 12 finished with value: 0.7066374367596374 and parameters: {'num_leaves': 31, 'n_estimators': 12, 'learning_rate': 0.027905500296878296, 'max_depth': 10}. Best is trial 1 with value: 0.7265362868989825.
[I 2026-04-08 19:55:13,738] Trial 13 finished with value: 0.7267532279483224 and parameters: {'num_leaves': 24, 'n_estimators': 353, 'learning_rate': 0.02949185283354324, 'max_depth': 6}. Best is trial 13 with value: 0.7267532279483224.
[I 2026-04-08 19:55:15,797] Trial 14 finished with value: 0.7245723417996868 and parameters: {'num_leaves': 48, 'n_estimators': 587, 'learning_rate': 0.03401937012002483, 'max_depth': 9}. Best is trial 13 with value: 0.7267532279483224.
[I 2026-04-08 19:55:16,611] Trial 15 finished with value: 0.7247812060343527 and parameters: {'num_leaves': 23, 'n_estimators': 383, 'learning_rate': 0.08266447414263328, 'max_depth': 5}. Best is trial 13 with value: 0.7267532279483224.
[I 2026-04-08 19:55:18,499] Trial 16 finished with value: 0.7269543808350418 and parameters: {'num_leaves': 44, 'n_estimators': 669, 'learning_rate': 0.010147085546943749, 'max_depth': 7}. Best is trial 16 with value: 0.7269543808350418.
[I 2026-04-08 19:55:20,295] Trial 17 finished with value: 0.7276395944021022 and parameters: {'num_leaves': 68, 'n_estimators': 709, 'learning_rate': 0.01021124420389063, 'max_depth': 5}. Best is trial 17 with value: 0.7276395944021022.
[I 2026-04-08 19:55:21,153] Trial 18 finished with value: 0.7259125631087944 and parameters: {'num_leaves': 66, 'n_estimators': 734, 'learning_rate': 0.010220853888616585, 'max_depth': 3}. Best is trial 17 with value: 0.7276395944021022.
[I 2026-04-08 19:55:23,239] Trial 19 finished with value: 0.7277352735913158 and parameters: {'num_leaves': 68, 'n_estimators': 783, 'learning_rate': 0.0101124447862874, 'max_depth': 5}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:24,728] Trial 20 finished with value: 0.7271990790823218 and parameters: {'num_leaves': 98, 'n_estimators': 863, 'learning_rate': 0.019100626133207333, 'max_depth': 4}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:25,975] Trial 21 finished with value: 0.7272995641589998 and parameters: {'num_leaves': 100, 'n_estimators': 845, 'learning_rate': 0.013097565565942408, 'max_depth': 4}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:27,591] Trial 22 finished with value: 0.7273021224260909 and parameters: {'num_leaves': 69, 'n_estimators': 838, 'learning_rate': 0.01326824724769118, 'max_depth': 5}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:29,455] Trial 23 finished with value: 0.7271519886945061 and parameters: {'num_leaves': 69, 'n_estimators': 854, 'learning_rate': 0.012566751887387782, 'max_depth': 5}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:31,179] Trial 24 finished with value: 0.7250844885980228 and parameters: {'num_leaves': 77, 'n_estimators': 765, 'learning_rate': 0.020412628766957843, 'max_depth': 5}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:32,732] Trial 25 finished with value: 0.7271023583129355 and parameters: {'num_leaves': 63, 'n_estimators': 647, 'learning_rate': 0.012702936698097252, 'max_depth': 5}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:33,489] Trial 26 finished with value: 0.727351021874207 and parameters: {'num_leaves': 78, 'n_estimators': 802, 'learning_rate': 0.022452975986643826, 'max_depth': 3}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:34,094] Trial 27 finished with value: 0.7269461212870043 and parameters: {'num_leaves': 80, 'n_estimators': 641, 'learning_rate': 0.022780374907865962, 'max_depth': 3}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:35,087] Trial 28 finished with value: 0.7272889290772345 and parameters: {'num_leaves': 91, 'n_estimators': 917, 'learning_rate': 0.023097571461620964, 'max_depth': 3}. Best is trial 19 with value: 0.7277352735913158.
[I 2026-04-08 19:55:36,543] Trial 29 finished with value: 0.7243369995006264 and parameters: {'num_leaves': 61, 'n_estimators': 773, 'learning_rate': 0.03918469167027377, 'max_depth': 4}. Best is trial 19 with value: 0.7277352735913158.

In [19]:
def objective_catboost(trial):
    params = {
        'iterations': trial.suggest_int('iterations',100,1000),
        'depth': trial.suggest_int('depth', 4, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'verbose': False
    }
    
    model = CatBoostClassifier(**params, random_seed=RANDOM_STATE)
    model.fit(xtrain_new, ytrain_new, cat_features=cat_features)

    preds = model.predict_proba(xval)[:,1]
    return roc_auc_score(yval, preds)

catboost_study = optuna.create_study(direction='maximize')
catboost_study.optimize(objective_catboost, n_trials=10)

[I 2026-04-08 19:59:15,090] A new study created in memory with name: no-name-c493c68a-d92e-4441-aa19-46f806923f72
[I 2026-04-08 20:00:01,549] Trial 0 finished with value: 0.7536346214232502 and parameters: {'iterations': 606, 'depth': 5, 'learning_rate': 0.18076254298493566}. Best is trial 0 with value: 0.7536346214232502.
[I 2026-04-08 20:01:43,104] Trial 1 finished with value: 0.7410022457199461 and parameters: {'iterations': 830, 'depth': 8, 'learning_rate': 0.18115831365558696}. Best is trial 0 with value: 0.7536346214232502.
[I 2026-04-08 20:03:25,949] Trial 2 finished with value: 0.747522610695486 and parameters: {'iterations': 638, 'depth': 10, 'learning_rate': 0.013199754709576456}. Best is trial 0 with value: 0.7536346214232502.
[I 2026-04-08 20:05:20,767] Trial 3 finished with value: 0.7475591390948823 and parameters: {'iterations': 835, 'depth': 7, 'learning_rate': 0.01369796571866057}. Best is trial 0 with value: 0.7536346214232502.
[I 2026-04-08 20:09:20,268] Trial 4 finished with value: 0.7537524844428124 and parameters: {'iterations': 856, 'depth': 9, 'learning_rate': 0.03349643678971391}. Best is trial 4 with value: 0.7537524844428124.
[I 2026-04-08 20:12:12,166] Trial 5 finished with value: 0.7547279334113776 and parameters: {'iterations': 710, 'depth': 8, 'learning_rate': 0.04726088357559401}. Best is trial 5 with value: 0.7547279334113776.
[I 2026-04-08 20:12:28,942] Trial 6 finished with value: 0.6995738968606116 and parameters: {'iterations': 149, 'depth': 8, 'learning_rate': 0.012472719168072298}. Best is trial 5 with value: 0.7547279334113776.
[I 2026-04-08 20:14:36,380] Trial 7 finished with value: 0.7474540125907673 and parameters: {'iterations': 702, 'depth': 8, 'learning_rate': 0.015023519551760832}. Best is trial 5 with value: 0.7547279334113776.
[I 2026-04-08 20:16:25,536] Trial 8 finished with value: 0.7480835838485927 and parameters: {'iterations': 751, 'depth': 5, 'learning_rate': 0.023503039812899973}. Best is trial 5 with value: 0.7547279334113776.
[I 2026-04-08 20:17:19,937] Trial 9 finished with value: 0.7541536207227236 and parameters: {'iterations': 317, 'depth': 7, 'learning_rate': 0.12172894445404898}. Best is trial 5 with value: 0.7547279334113776.

In [20]:
best_lgbm = LGBMClassifier(**study.best_params, random_state=RANDOM_STATE)
best_lgbm.fit(xtrain, ytrain)

final_lgbm = best_lgbm.predict_proba(xtest)[:, 1]
final_roc_auc = roc_auc_score(ytest, final_preds)
final_roc_auc

0.7325832095846545

In [21]:
best_lgbm = LGBMClassifier(**lgbm_study.best_params, random_state=RANDOM_STATE)
best_lgbm.fit(xtrain, ytrain)
final_lgbm = best_lgbm.predict_proba(xtest)[:, 1]
final_roc_auc = roc_auc_score(ytest, final_lgbm)
final_roc_auc

0.7356378140902512

## Quiz

Поделитесь своими результатами!